# Generated by Django 3.2.9 on 2022-02-18 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='creditoventa',
            name='tipopagos',
        ),
    ]
