# Generated by Django 3.2.9 on 2022-02-18 11:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_creditoventa_tipopagos'),
    ]

    operations = [
        migrations.AddField(
            model_name='creditoventa',
            name='tipopagos',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='creditoventa_tipopago', to='core.tipopago'),
        ),
    ]
