# Generated by Django 3.2.9 on 2022-03-06 06:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20220304_1037'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='empresas',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='producto_empresa', to='core.empresa'),
        ),
    ]
