# Generated by Django 3.2.9 on 2022-04-04 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_producto_empresas'),
    ]

    operations = [
        migrations.AddField(
            model_name='actividad',
            name='orden',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
