# Generated by Django 3.2.9 on 2022-06-16 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_actividad_orden'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='tiene_igv',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
