# Generated by Django 3.2.9 on 2022-06-16 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_producto_tiene_igv'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='tipocomprobante',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='venta',
            name='tipoigv',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='venta',
            name='tipopago',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
