# Generated by Django 3.2.9 on 2022-06-18 06:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20220617_2205'),
    ]

    operations = [
        migrations.AddField(
            model_name='tienda',
            name='clientesportales',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='tienda_clienteportal', to='core.clienteportal'),
        ),
    ]
