# Generated by Django 3.2.9 on 2022-06-19 08:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_tienda_clientesportales'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreditoBoletaFactura',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_pagar', models.CharField(max_length=100)),
                ('monto_pagar', models.DecimalField(decimal_places=15, max_digits=30)),
                ('estado', models.CharField(max_length=3)),
                ('fecha_creacion', models.DateField(auto_now_add=True)),
                ('ventas', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='creditoboletafactura_venta', to='core.venta')),
            ],
        ),
    ]
