# Generated by Django 3.2.9 on 2022-06-19 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_creditoboletafactura'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditoboletafactura',
            name='fecha_pagar',
            field=models.DateField(max_length=100),
        ),
    ]
