# Generated by Django 3.2.9 on 2022-06-19 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_creditoboletafactura_fecha_pagar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditoboletafactura',
            name='fecha_pagar',
            field=models.DateField(blank=True, null=True),
        ),
    ]
