# Generated by Django 3.2.9 on 2022-06-20 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_alter_creditoboletafactura_fecha_pagar'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipomoneda',
            name='abreviacion',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
