# Generated by Django 3.2.9 on 2022-06-21 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_tipomoneda_abreviacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='comprobanteaprobado',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
